# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_1_score', models.PositiveIntegerField(blank=True, null=True)),
                ('player_2_score', models.PositiveIntegerField(blank=True, null=True)),
                ('player_1_init', models.ForeignKey(blank=True, help_text='Set for first round matches', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_game_match', to='players.Player')),
                ('player_2_init', models.ForeignKey(blank=True, help_text='Set for first round matches', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_game_match', to='players.Player')),
                ('previous_match_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsequent_match_1', to='matches.Match')),
                ('previous_match_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsequent_match_2', to='matches.Match')),
            ],
        ),
    ]
