# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20160322_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='round_index',
            field=models.PositiveIntegerField(default=1, help_text='The order of this match in the round (used for positioning).'),
            preserve_default=False,
        ),
    ]
