# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_pool'),
        ('matches', '0004_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('bracket', models.ForeignKey(blank=True, help_text='Set either the bracket or pool field', null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.Bracket')),
                ('pool', models.ForeignKey(blank=True, help_text='Set either the bracket or pool field', null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Pool')),
            ],
        ),
    ]
