# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='bracket',
        ),
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.Round'),
        ),
    ]
