# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_auto_20160328_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.DateTimeField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='matches.Match')),
            ],
        ),
    ]
