# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_matchnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='matches.Tournament'),
            preserve_default=False,
        ),
    ]
